obj/include/*			usr/include/makerbot
src/main/skeinforge/*		usr/share/skeinforge
obj/libconveyor.a				usr/lib/makerbot
obj/etc/conveyor.conf			etc
obj/module						usr/share/conveyor/lib
submodule/conveyor_bins/python/pyserial-2.7_mb2.1-py2.7.egg	usr/share/conveyor
data/conveyor.conf				etc/init
wrapper/conveyord				usr/bin
wrapper/conveyor_service.py		usr/share/conveyor
virtualenv.py                   usr/share/conveyor

